##user create
POST http://localhost:3000/api/users
content-type: application/json

{
    "user_name": "omar1",
    "first_name": "omar1",
    "last_name": "nawito1",
    "email": "o_mohsen1@hotmail.com",
    "password": "1234567891"
}
### get user
GET http://localhost:3000/api/users/52b1df27-6c1f-4106-8aad-7b62d0fa1c91
content-type: application/json
### get all users
GET http://localhost:3000/api/users
content-type: application/json
### get all products
GET http://localhost:3000/api/products
content-type: application/json
### get specific product
GET http://localhost:3000/api/products/4d0582fc-c39e-4c69-87cd-fdb221a443b3
content-type: application/json
### create product
POST http://localhost:3000/api/products
content-type: application/json

{
    "name": "iphone13",
    "price":215
}