
##user create
POST http://localhost:3000/api/users
content-type: application/json

{
    "user_name": "omarzz",
    "first_name": "omarzz",
    "last_name": "nawitozz",
    "email": "o_mohsenzzz@hotmail.com",
    "password": "1234567891"
}
### get user
GET http://localhost:3000/api/users/52b1df27-6c1f-4106-8aad-7b62d0fa1c91
content-type: application/json
### delete user
DELETE http://localhost:3000/api/users/52b1df27-6c1f-4106-8aad-7b62d0fa1c91
content-type: application/json
### get all users
GET http://localhost:3000/api/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMjI3MzJhMzctNjEyNC00MmI3LWFkZTYtZjhkMzMyZWY4NzI5IiwiZW1haWwiOiJvX21vaHNlbnp6ekBob3RtYWlsLmNvbSIsInVzZXJfbmFtZSI6Im9tYXJ6eiIsImZpcnN0X25hbWUiOiJvbWFyenoiLCJsYXN0X25hbWUiOiJuYXdpdG96eiJ9LCJpYXQiOjE2NDYxMjkyNzB9.A_4PWwgnVKT31c57esiGPQNb94S8kJYWXJUQdOaQnj4
### get all products
GET http://localhost:3000/api/products
content-type: application/json
### get specific product
GET http://localhost:3000/api/products/4d0582fc-c39e-4c69-87cd-fdb221a443b3
content-type: application/json
### create product
POST http://localhost:3000/api/products
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYWE5OWUyOWMtODJlYi00Nzk5LTg2NzMtYzA1NjZjZWIzZjFiIiwiZW1haWwiOiJvX21vaHNlbjEyM0Bob3RtYWlsLmNvbSIsInVzZXJfbmFtZSI6Im9tYXIxMiIsImZpcnN0X25hbWUiOiJvbWFyMTIiLCJsYXN0X25hbWUiOiJuYXdpdG8xMiJ9LCJpYXQiOjE2NDU4OTQzNTN9.V87pR1875iL1CHVmDoF6na0BT7akJ6vOQlaETH-u7hw

{
    "name": "iphone13",
    "price":215
}
### create order
POST http://localhost:3000/api/orders
content-type: application/json

{
    "users_id": "52b1df27-6c1f-4106-8aad-7b62d0fa1c91",
    "order_status": "completed",
    "products_id": "4d0582fc-c39e-4c69-87cd-fdb221a443b3",
    "product_quantity": 5
}
### get all orders
GET http://localhost:3000/api/orders
content-type: application/json
### get all orders
POST http://localhost:3000/api/users/authenticate
content-type: application/json

{
    "first_name": "omarzz",
    "password": "1234567891"
}